- name: install some apt packages
  apt: "name={{ item }} state=present"
  with_items:
    - openvpn

- name: copy openvpn config
  copy: src={{configfile}} dest=/etc/openvpn/vpnclient.conf mode=0400
  notify:
  - restart openvpn

- name: fix openvpn defaults for init script
  lineinfile: dest=/etc/default/openvpn regexp="^AUTOSTART=" line="AUTOSTART=\"all\"" state=present create=yes
  notify:
  - restart openvpn

