- name: make sure mountpoint exists with correct permissions
  file: path="{{path}}" state=directory mode="{{perm}}"

- name: check if loopfile exists
  stat: path="{{src}}"
  register: loopfsfile

- name: create loopfile
  command: dd if=/dev/zero of="{{src}}" bs="{{bs}}" count="{{count}}"
  when: not (loopfsfile.stat.exists is defined and loopfsfile.stat.exists)

- name: format loopfile filesystem
  filesystem: fstype="{{fstype}}" dev="{{src}}"
  when: not (loopfsfile.stat.exists is defined and loopfsfile.stat.exists)

- name: mount loopfile
  mount:
    name: "{{path}}"
    src: "{{src}}"
    fstype: "{{fstype}}"
    opts: "{{opts}}"
    state: mounted

- name: make sure mounted filesystem also has correct permissions
  file: path="{{path}}" state=directory mode="{{perm}}"
