- stat: path=/usr/bin/docker
  register: docker

- name: fetch docker install script
  get_url: url=https://get.docker.com dest=/tmp/install-docker.sh mode=0555
  when: not docker.stat.exists

- name: install docker
  shell: /tmp/install-docker.sh
  when: not docker.stat.exists

- name: add default user to docker group
  user: name="{{ansible_user}}" groups=docker append=yes

- name: install packages
  apt: "name={{ item }} state=present"
  with_items:
      - python3-pip
      - python-pip

- name: install pip packages
  pip: "name=docker state=present executable={{item}}"
  with_items:
      - pip
      - pip3

- name: check bridges
  shell: "docker network inspect {{ item.name }}"
  ignore_errors: yes
  with_items: "{{ bridges | default([]) }}"
  register: dockerbridgesres

- name: create bridges
  shell: "docker network create --subnet={{ item.item.subnet }} -o com.docker.network.bridge.name={{item.item.name}} {{item.item.name}}"
  when: item.rc == 1
  with_items: "{{ dockerbridgesres.results }}"

- name: disable iptables mangling
  lineinfile: dest='/lib/systemd/system/docker.service' state=present regexp='^ExecStart=/usr/bin/dockerd -H fd://' line='ExecStart=/usr/bin/dockerd -H fd:// --iptables=false'
  notify:
    - restart docker

