- name: install some apt packages
  apt: "name={{ item }} state=present"
  with_items:
    - openvpn
    - easy-rsa
    - python3-pip

- name: install pip3 packages
  pip: "name={{ item }} state=present executable=pip3"
  with_items:
      - jinja2-cli

- name: copy openvpn files
  synchronize: src={{vpnserver_configdir}}/ dest=/etc/openvpn/
  register: copyvpnfiles

- name: fix openvpn defaults for init script
  lineinfile: dest=/etc/default/openvpn regexp="^AUTOSTART=" line="AUTOSTART=\"all\"" state=present create=yes
  register: ovpninit

- name: reload systemctl if it exists
  command: systemctl daemon-reload
  failed_when: false

- name: restart openvpn if needed
  shell: systemctl daemon-reload && systemctl restart openvpn
  when: copyvpnfiles.changed

- name: make tools directory
  file: dest=/etc/openvpn/tools state=directory

- name: copy some files
  copy: src={{item}} dest=/etc/openvpn/tools/{{item}} mode=0755
  with_items:
    - gen-keys
    - make-client-config
    - example-server-routed.conf
    - example-server-bridged.conf
    - client-bridged.conf.j2
    - client-routed.conf.j2
    - up.sh

- name: store our IP address
  copy: dest=/etc/openvpn/tools/serverip content="{{ansible_host}}"


