  - name: check if shorewall is installed
    apt: "name={{ item }} state=present"
    with_items:
      - shorewall
  
  - name: make sure shorewall is enabled
    service: name=shorewall enabled=yes use=service

  - name: configure default shorewall rules
    lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
    with_items: "{{default_rules}}"
    notify: 
        - restart shorewall

  - name: configure custom shorewall rules
    lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
    with_items: "{{rules}}"
    notify: 
        - restart shorewall

  - name: enable shorewall to start from boot
    lineinfile: "dest=/etc/default/shorewall regexp='^startup=' line='startup=1' state=present"

  - name: make shorewall aware of Docker
    lineinfile: "dest=/etc/shorewall/shorewall.conf regexp='^DOCKER=' line='DOCKER=Yes' state=present"
