- name: building docker containers
  shell: "docker-compose build"
  args:
      chdir: "{{item}}"
  loop: "{{build_dirs}}"

- name: (building and) starting docker containers
  shell: "docker-compose up -d"
  args:
      chdir: "{{item}}"
  loop: "{{up_dirs}}"
